version: '3'
services:

  client:
    build:
      context: ./client
      dockerfile: ../.config/Dockerfile-client
    image: shintolin4/client
    env_file: ./.config/env.env
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729" # hot reload
    depends_on:
      - server

  storybook:
    build:
      context: ./client
      dockerfile: ../.config/Dockerfile-storybook
    image: shintolin4/storybook
    env_file: ./.config/env.env
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"

  server:
    build:
      context: ./server
      dockerfile: ../.config/Dockerfile-server
    image: shintolin4/server
    env_file: ./.config/env.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - shintolin4-postgres

  shintolin4-postgres:
    image: "postgres:9.6" # AWS Aurora Postgres is currently compatible to 9.6.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - shintolin4-postgres-data:/var/lib/postgresql/data
      - ./.config/postgres:/docker-entrypoint-initdb.d
    ports:
      - "3100:5432"

volumes:

  shintolin4-postgres-data:
    external: true
