FROM node:8-alpine

WORKDIR /usr/src/app

COPY . .

# install OS dependencies
RUN apk add --no-cache bash
RUN apk add --no-cache curl
RUN apk add --no-cache ncurses

# install yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# install app dependencies
RUN yarn install

CMD yarn run storybook
